-- Insertion des données de test pour la base de données H2

-- Adresses de facturation
INSERT INTO BILL_TO_ADDRESS (BILL_TO_ADDRESS_ID, FIRST_NAME, LAST_NAME, ADDRESS_1, ADDRESS_2, CITY, STATE, ZIP_CODE)
VALUES ('BILL001', 'John', 'Doe', '123 Billing St', 'Apt 456', 'Paris', 'IDF', '75001');

-- Adresses de livraison
INSERT INTO SHIP_TO_ADDRESS (SHIP_TO_ADDRESS_ID, FIRST_NAME, LAST_NAME, ADDRESS_1, ADDRESS_2, CITY, STATE, ZIP_CODE)
VALUES ('SHIP001', 'John', 'Doe', '123 Shipping St', 'Apt 456', 'Paris', 'IDF', '75001');

-- Informations de paiement
INSERT INTO PAYMENT_INFO (PAYMENT_ID, PAYMENT_STATUS, CARD_TYPE, AUTHORIZED_AMOUNT, COLLECTED_AMOUNT)
VALUES ('PAY123', 'AUTHORIZED', 'VISA', 100.00, 0.00);

-- Frais
INSERT INTO CHARGES (CHARGES_ID, LINE_SUB_TOTAL, TOTAL_CHARGES, SALES_TAX, GRAND_TOTAL)
VALUES ('CHARGES001', 95.00, 95.00, 5.00, 100.00);

-- Frais de ligne
INSERT INTO LINE_CHARGE (LINE_CHARGE_ID, TOTAL_CHARGES)
VALUES ('LC123', 95.00);

-- Lignes de commande
INSERT INTO ORDER_LINE (LINE_ITEM_ID, CUSTOMER_ORDER_ID, SHIP_NODE, SHIP_NODE_DESC, LEVEL_OF_SERVICE, PRIME_LINE_NO, SUB_LINE_NO, CUSTOMER_SKU, SKU_DESCRIPTION, EST_ARRIVAL_DATE, STATUS, RESHIPPED_BEFORE, SHIP_TO_ADDRESS_ID, LINE_CHARGE_ID)
VALUES ('ITEM123', 'ORD12345', 'STORE001', 'Store Paris', 'STANDARD', '1', '1', 'SKU001', 'Smartphone', '2025-05-10', 'PROCESSING', 'NO', 'SHIP001', 'LC123');

-- Commandes
INSERT INTO SALES_ORDER (CUSTOMER_ORDER_ID, PRIMARY_PHONE, CUSTOMER_EMAIL_ID, ORDER_STATUS, FIRST_NAME, ORDER_DATE, PROFILE_ID, LAST_NAME, ENTRY_TYPE, BILL_TO_ADDRESS_ID, SHIP_TO_ADDRESS_ID, LINE_ITEM_ID, PAYMENT_ID, CHARGES_ID)
VALUES ('ORD12345', '1234567890', 'client@example.com', 'PROCESSING', 'John', '2025-05-01', 'PROF123', 'Doe', 'WEB', 'BILL001', 'SHIP001', 'ITEM123', 'PAY123', 'CHARGES001');

-- Inventaire
INSERT INTO INVENTORY (SKU_ID, STORE_ID, QTY)
VALUES ('SKU001', 'STORE001', 10);

-- Frais de livraison
INSERT INTO SHIPPING (SKU_ID, STANDARD_SHIPPING, EXPEDITED_SHIPPING, EXPRESS_SHIPPING)
VALUES ('SKU001', 5.99, 9.99, 14.99);

-- Informations produit
INSERT INTO PRODUCT_INFO (PRODUCT_ID, NAME, DESCRIPTION, MANUFACTURER)
VALUES ('SKU001', 'Smartphone', 'Smartphone haut de gamme', 'TechCorp');
