version: '3.8'

services:
  payment-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: payment-service
    ports:
      - "8084:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8082
    networks:
      - oms-network
    volumes:
      - ../oms-log.txt:/app/oms-log.txt
    restart: unless-stopped

networks:
  oms-network:
    driver: bridge
