version: '3.8'

services:
  # Service de base de données H2
  h2-database:
    image: oscarfonts/h2
    container_name: h2-database
    ports:
      - "8082:81"    # Interface web H2
      - "1521:1521"  # Port TCP pour les connexions JDBC
    environment:
      - H2_OPTIONS=-ifNotExists
    volumes:
      - h2-data:/opt/h2-data
    networks:
      - oms-network

  # Service Fulfillment Controller
  fulfillment-controller:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: fulfillment-controller
    ports:
      - "8083:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2-database:1521/fulfillment;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_SQL_INIT_MODE=always
      - SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true
    volumes:
      - ./data.sql:/app/data.sql
    depends_on:
      - h2-database
    networks:
      - oms-network

networks:
  oms-network:
    driver: bridge

volumes:
  h2-data:
    driver: local
