version: '3.8'

services:
  # Service Email Service
  email-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: email-service
    ports:
      - "8083:8081"
    networks:
      - oms-network

networks:
  oms-network:
    driver: bridge
