-- Initialisation des données de test pour la table SHIPPING
INSERT INTO SHIPPING (SKU_ID, STANDARD_SHIPPING, EXPEDITED_SHIPPING, EXPRESS_SHIPPING) VALUES ('SKU001', 5.99, 9.99, 14.99);
INSERT INTO SHIPPING (SKU_ID, STANDARD_SHIPPING, EXPEDITED_SHIPPING, EXPRESS_SHIPPING) VALUES ('SKU002', 7.99, 12.99, 18.99);
INSERT INTO SHIPPING (SKU_ID, STANDARD_SHIPPING, EXPEDITED_SHIPPING, EXPRESS_SHIPPING) VALUES ('SKU003', 4.99, 8.99, 12.99);
INSERT INTO SHIPPING (SKU_ID, STANDARD_SHIPPING, EXPEDITED_SHIPPING, EXPRESS_SHIPPING) VALUES ('SKU004', 6.99, 10.99, 16.99);
INSERT INTO SHIPPING (SKU_ID, STANDARD_SHIPPING, EXPEDITED_SHIPPING, EXPRESS_SHIPPING) VALUES ('SKU005', 8.99, 14.99, 20.99);
